### ISSUE TITLE
multithread

### ISSUE THREAD

**Issue by hitbg-yjm** [CNR-STIIMA-IRAS/cnr_logger#13]
This code crashes when using multithreading to print logs
//

#include <cnr_logger/cnr_logger.h>
#include <ros/callback_queue.h>
#include <ros/ros.h>

void timerCallback(const std::shared_ptr<cnr_logger::TraceLogger> &logger,
                   const std::string &msg, const ros::WallTimerEvent &e) {

  std::string gg;
  for (int i = 0; i < 300; ++i) {
    for (int j = 0; j < 20; ++j) {
      gg += "gggg";
    }
  }
  CNR_WARN(
      *logger,
      "this is: "
          << msg << " "
          << gg << " "
          << std::fixed << ros::WallTime::now().toSec());
}
int main(int argc, char **argv) {

  ros::init(argc, argv, "mmm_test", ros::InitOption::AnonymousName);
  ros::NodeHandle pnh("~");

  auto logger = std::make_shared<cnr_logger::TraceLogger>(
      "mmm_node", pnh.getNamespace(), true);

  ros::CallbackQueue queue;
  pnh.setCallbackQueue(&queue);
  ros::WallTimer t1 = pnh.createWallTimer(
      ros::WallDuration(0.01), [logger](const ros::WallTimerEvent &e) {
        return timerCallback(logger, "t1", std::forward<decltype(e)>(e));
      });

  ros::WallTimer t2 = pnh.createWallTimer(
      ros::WallDuration(0.01), [logger](const ros::WallTimerEvent &e) {
        return timerCallback(logger, "t2", std::forward<decltype(e)>(e));
      });

  ros::WallTimer t3 = pnh.createWallTimer(
      ros::WallDuration(0.01), [logger](const ros::WallTimerEvent &e) {
        return timerCallback(logger, "t3", std::forward<decltype(e)>(e));
      });

  ros::WallTimer t4 = pnh.createWallTimer(
      ros::WallDuration(0.01), [logger](const ros::WallTimerEvent &e) {
        return timerCallback(logger, "t4", std::forward<decltype(e)>(e));
      });

  std::cout << cnr_logger::BOLDCYAN() << "START" << cnr_logger::RESET() << std::endl;

  ros::AsyncSpinner async_spinner(8, &queue);
  async_spinner.start();

  ros::waitForShutdown();
  async_spinner.stop();
  ROS_WARN("goodbye");
  return 0;
}

///////////////////////////////////

gdb  error：
Thread 13 "mmm_node" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffd6ffd700 (LWP 23330)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff64a77f1 in __GI_abort () at abort.c:79
#2  0x00007ffff6afc957 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff6b02ae6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff6b02b21 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff6b02d54 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff6afe85d in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00007ffff735ad70 in log4cxx::helpers::SimpleDateFormatImpl::NumericToken::format(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, apr_time_exp_t const&, log4cxx::helpers::Pool&) const () from /usr/lib/x86_64-linux-gnu/liblog4cxx.so.10
#8  0x00007ffff735998e in log4cxx::helpers::SimpleDateFormat::format(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, long long, log4cxx::helpers::Pool&) const ()
   from /usr/lib/x86_64-linux-gnu/liblog4cxx.so.10
#9  0x00007ffff72eef65 in log4cxx::pattern::CachedDateFormat::format(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, long long, log4cxx::helpers::Pool&) const ()
   from /usr/lib/x86_64-linux-gnu/liblog4cxx.so.10
#10 0x00007ffff734351e in log4cxx::PatternLayout::format(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, log4cxx::helpers::ObjectPtrT<log4cxx::spi::LoggingEvent> const&, log4cxx::helpers::Pool&) const () from /usr/lib/x86_64-linux-gnu/liblog4cxx.so.10
#11 0x00007ffff7bbd42c in log4cxx::ColorPatternLayout::format(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, log4cxx::helpers::ObjectPtrT<log4cxx::spi::LoggingEvent> const&, log4cxx::helpers::Pool&) const () from /home/yjm/workspace_2023/cnr_logger_multithread/devel/lib/libcnr_logger.so
#12 0x00007ffff737883f in log4cxx::WriterAppender::subAppend(log4cxx::helpers::ObjectPtrT<log4cxx::spi::LoggingEvent> const&, log4cxx::helpers::Pool&) () from /usr/lib/x86_64-linux-gnu/liblog4cxx.so.10
#13 0x00007ffff7355a79 in log4cxx::rolling::RollingFileAppenderSkeleton::subAppend(log4cxx::helpers::ObjectPtrT<log4cxx::spi::LoggingEvent> const&, log4cxx::helpers::Pool&) ()
   from /usr/lib/x86_64-linux-gnu/liblog4cxx.so.10
#14 0x00007ffff72e8665 in log4cxx::AppenderSkeleton::doAppend(log4cxx::helpers::ObjectPtrT<log4cxx::spi::LoggingEvent> const&, log4cxx::helpers::Pool&) () from /usr/lib/x86_64-linux-gnu/liblog4cxx.so.10
#15 0x00007ffff72e660f in log4cxx::helpers::AppenderAttachableImpl::appendLoopOnAppenders(log4cxx::helpers::ObjectPtrT<log4cxx::spi::LoggingEvent> const&, log4cxx::helpers::Pool&) ()
   from /usr/lib/x86_64-linux-gnu/liblog4cxx.so.10
#16 0x00007ffff732badd in log4cxx::Logger::callAppenders(log4cxx::helpers::ObjectPtrT<log4cxx::spi::LoggingEvent> const&, log4cxx::helpers::Pool&) const () from /usr/lib/x86_64-linux-gnu/liblog4cxx.so.10
#17 0x00007ffff732bd0e in log4cxx::Logger::forcedLog(log4cxx::helpers::ObjectPtrT<log4cxx::Level> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, log4cxx::spi::LocationInfo const&) const () from /usr/lib/x86_64-linux-gnu/liblog4cxx.so.10
#18 0x000055555555e8ea in timerCallback (logger=std::shared_ptr<cnr_logger::TraceLogger> (use count 9, weak count 0) = {...}, msg="t3", e=...)
    at /home/yjm/workspace_2023/cnr_logger_multithread/src/mmm/src/mmm_node.cpp:18
#19 0x000055555555ee96 in <lambda(const ros::WallTimerEvent&)>::operator()(const ros::WallTimerEvent &) const (__closure=0x555555797e38, e=...)
    at /home/yjm/workspace_2023/cnr_logger_multithread/src/mmm/src/mmm_node.cpp:47
#20 0x0000555555560542 in boost::detail::function::void_function_obj_invoker1<main(int, char**)::<lambda(const ros::WallTimerEvent&)>, void, const ros::WallTimerEvent&>::invoke(boost::detail::function::function_buffer &, const ros::WallTimerEvent &) (function_obj_ptr=..., a0=...) at /usr/local/include/boost/function/function_template.hpp:159
#21 0x00007ffff78d2fa7 in ros::TimerManager<ros::WallTime, ros::WallDuration, ros::WallTimerEvent>::TimerQueueCallback::call() () from /opt/ros/melodic/lib/libroscpp.so
#22 0x00007ffff7906559 in ros::CallbackQueue::callOneCB(ros::CallbackQueue::TLS*) () from /opt/ros/melodic/lib/libroscpp.so
#23 0x00007ffff7907845 in ros::CallbackQueue::callOne(ros::WallDuration) () from /opt/ros/melodic/lib/libroscpp.so
#24 0x00007ffff795ec84 in ros::AsyncSpinnerImpl::threadFunc() () from /opt/ros/melodic/lib/libroscpp.so
#25 0x00007ffff5a0b79d in thread_proxy () from /usr/local/lib/libboost_thread.so.1.65.1
#26 0x00007ffff55dc6db in start_thread (arg=0x7fffd6ffd700) at pthread_create.c:463
#27 0x00007ffff658861f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
(gdb)

**Comment by xiaoxiaotao** [comment]
I have the same problem. Have you solved it?
